# Generated by Django 4.0.4 on 2022-10-28 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.JSONField(default=dict)),
                ('updated_by', models.JSONField(default=dict)),
                ('code', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('sec_id', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('uom', models.CharField(max_length=180)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('divider', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('bill_item_code', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.JSONField(default=dict)),
                ('generic_drug', models.JSONField(default=dict)),
                ('is_drug', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.JSONField(default=dict)),
                ('product', models.JSONField(default=dict)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.JSONField(default=dict)),
                ('updated_by', models.JSONField(default=dict)),
                ('move_id', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SELL', 'Sell'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment')], max_length=128)),
                ('source_location', models.JSONField(default=dict)),
                ('destination_location', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], max_length=128)),
                ('approved_by', models.JSONField(default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.JSONField(default=dict)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'StockMovements',
            },
        ),
        migrations.CreateModel(
            name='StockMovementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('move_id', models.CharField(blank=True, editable=False, max_length=256, null=True)),
                ('product', models.JSONField(default=dict)),
                ('quantity', models.IntegerField()),
                ('source_location', models.JSONField(default=dict)),
                ('destination_location', models.JSONField(default=dict)),
                ('approved_by', models.JSONField(default=dict)),
                ('approved_at', models.DateTimeField(null=True)),
                ('cancelled_by', models.JSONField(default=dict)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'StockMovementLines',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.JSONField(default=dict)),
                ('updated_by', models.JSONField(default=dict)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('INNOVATION LOSS', 'Innovation Loss'), ('CONSUMPTION', 'Consumption'), ('STORE', 'Store')], max_length=218)),
            ],
            options={
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='inventory.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
