# Generated by Django 4.0.4 on 2022-11-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovementline',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=128),
            preserve_default=False,
        ),
    ]
