# Generated by Django 4.0.4 on 2023-02-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmovement_options_stockmovement_moved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('INVENTORY LOSS', 'Inventory Loss'), ('CONSUMPTION', 'Consumption'), ('STORE', 'Store'), ('SUPPLIER', 'Supplier')], max_length=218),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'name')},
        ),
    ]
