# Generated by Django 4.0.4 on 2022-06-11 11:20

from django.db import migrations, models
import django.db.models.deletion
from api.apps.laboratory import models as lab_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('uom', models.CharField(max_length=256)),
                ('reference_range', models.JSONField()),
                ('type', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.JSONField(default=dict)),
                ('asn', models.CharField(default=lab_models.generate_asn_lab_order, editable=False, max_length=80, unique=True)),
                ('stat', models.BooleanField(default=False)),
                ('service_center', models.JSONField()),
                ('referral_facility', models.JSONField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('lab_panels', models.JSONField(default=list)),
                ('lab_panel_orders', models.JSONField(default=list)),
                ('ordered_by', models.JSONField(default=dict)),
                ('ordered_datetime', models.DateTimeField(auto_now_add=True)),
                ('ordering_physician', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabSpecimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.CharField(max_length=256)),
                ('type', models.JSONField(default=dict)),
                ('comments', models.JSONField(blank=True, default=list, null=True)),
                ('audit_log', models.JSONField(blank=True, default=list, null=True)),
                ('status', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabSpecimenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('order_no', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabPanelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.CharField(default=lab_models.generate_asn_lab_order, editable=False, max_length=80, unique=True)),
                ('patient', models.JSONField(default=dict)),
                ('panel', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=256, null=True)),
                ('audit_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.laborder')),
            ],
        ),
        migrations.CreateModel(
            name='LabPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('obv', models.JSONField()),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, max_length=256, null=True)),
                ('audit_log', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='laboratory.labunit')),
                ('specimen_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='laboratory.labspecimentype')),
            ],
        ),
    ]
