# Generated by Django 4.0.4 on 2022-06-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labpanelorder',
            name='asn',
        ),
        migrations.AddField(
            model_name='laborder',
            name='doc_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
