# Generated by Django 4.0.4 on 2022-07-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_labpanel_bill_item_code_labpanelorder_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labpanelorder',
            options={'permissions': (('take_specimen', 'Can take specimen'), ('recieve_specimen', 'Can receive specimen'), ('fill_result', 'Can fill result'), ('submit_result', 'Can submit result'), ('approve_reject_result', 'Can approve or reject result'), ('send_print_result', 'Can send or print result'))},
        ),
    ]
