# Generated by Django 4.0.4 on 2022-09-01 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_labpanelorder_is_result_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labspecimen',
            old_name='asn',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='labspecimen',
            name='audit_log',
        ),
        migrations.RemoveField(
            model_name='labspecimen',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='labspecimen',
            name='status',
        ),
        migrations.RemoveField(
            model_name='labspecimen',
            name='type',
        ),
        migrations.AddField(
            model_name='labspecimentype',
            name='specimen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='laboratory.labspecimen'),
        ),
    ]
