# Generated by Django 4.0.4 on 2022-10-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_rename_asn_labspecimen_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpanel',
            name='template',
            field=models.TextField(default='\n    <div class="border-right full-width">\n        <div class="border-bottom padding-round">\n            <b class="padding-round">PANEL: </b> {{ name }}\n            <span class="tab padding-round"><b>SPECIMEN:</b>{{ specimen.name|default_if_none:"---" }}</span>\n        </div>\n        <div class="d-flex border-bottom padding-round">\n            <div class="full-width text-center padding-round "><b>TEST</b></div>\n            <div class="full-width text-center padding-round "><b>RESULT</b></div>\n            <div class="full-width text-center padding-round "><b>UNIT</b></div>\n            <div class="full-width text-center padding-round"><b>REF. VALUE</b></div>\n        </div>\n        {% for observation in obv %}\n        <div class="d-flex border-bottom padding-round">\n            <div class="full-width text-center padding-round">{{ observation.name }}</div>\n            <div class="full-width text-center padding-round">{{ observation.value }}</div>\n            <div class="full-width text-center padding-round">{{ observation.uom }}</div>\n            <div class="full-width text-center padding-round">\n                {% for ref_range in observation.reference_range %}\n                <span>{{ ref_range.name }}</span>\n                {% endfor %}\n            </div>\n        </div>\n        {% endfor %}\n        <div class="border-bottom padding-round">\n            <div style="padding: 5px;"><b>Comment:</b>\n                <i>{{ comments|default_if_none:"---" }}</i>\n            </div>\n        </div>\n    </div>\n'),
        ),
    ]
