# Generated by Django 4.0.4 on 2022-11-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_labpanel_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpanelorder',
            name='panel_struct',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='labpanel',
            name='template',
            field=models.TextField(default='{% load data_types %}\n\n<div class="full-width m-top">\n    <div>\n        <div class="d-flex full-width border-bottom border-top">\n            <div class=" d-flex flex-1">\n            <div class="full-width border-right text-center padding-round"><b>Lab No.</b></div>\n            <div class="full-width border-right text-center padding-round">{{ asn }}</div>\n        </div>\n        <div class="d-flex rev-flex-dir flex-1">\n            <div class="d-flex full-width border-bottom">\n                <div class="full-width border-right text-center padding-round"><b>Collection Date/Time</b></div>\n                <div class="full-width text-center padding-round">{{ logs.specimen_taken_at }}</div>\n            </div>\n            <div class="d-flex full-width border-bottom">\n                <div class="full-width border-right text-center padding-round"><b>Received Date/Time</b></div>\n                <div class="full-width text-center padding-round">{{ logs.specimen_recieved_at }}</div>\n            </div>\n            <div class="d-flex full-width">\n                <div class="full-width border-right text-center padding-round"><b>Reported Date/Time</b></div>\n                <div class="full-width text-center padding-round">{{ logs.result_submitted_at }}</div>\n            </div>\n        </div>\n    </div>\n    <div class="d-flex full-width border-bottom">\n        <div class="border-right padding-round m-right"><b>SPECIMEN</b></div>\n        <div class="flex-1 padding-round m-left">{{ panel.specimen.name|default_if_none:"---" }}</div>\n    </div>\n    <div class="d-flex full-width border-bottom">\n        <div class="border-right padding-round m-right"><b>ORDERED</b></div>\n        <div class="flex-1 padding-round m-left">{{ panel.name }}</div>\n    </div>\n    <div class="d-flex full-width border-bottom">\n        <div class="border-right padding-round m-right"><b>COMMENTS</b></div>\n        <div class="flex-1 padding-round m-left">\n            {% comment %} {% for comment in logs_comments %} {% endcomment %}\n            <p> {{ logs_comments.0 }} </p>\n            {% comment %} {% endfor %} {% endcomment %}\n        </div>\n    </div>\n</div>\n<div class="d-flex border-bottom padding-round white-text-color" style="background-color: cornflowerblue;">\n    <div class="full-width text-center padding-round "><b>TEST</b></div>\n    <div class="full-width text-center padding-round "><b>RESULT</b></div>\n    <div class="full-width text-center padding-round "><b>UNIT</b></div>\n    <div class="full-width text-center padding-round"><b>REF. VALUE</b></div>\n</div>\n{% for observation in panel.obv %}\n<div class="d-flex border-bottom padding-round">\n    <div class="full-width text-center padding-round">{{ observation.name }}</div>\n    <div class="full-width text-center padding-round">{{ observation.value }}</div>\n    <div class="full-width text-center padding-round">{{ observation.uom }}</div>\n    <div class="full-width text-center padding-round">\n        {% for ref_range in observation.reference_range %}\n        <span>{{ ref_range.name }}</span>\n        {% endfor %}\n    </div>\n</div>\n{% endfor %}\n<div class="border-bottom padding-round">\n    <div style="padding: 5px;"><b>Comment:</b>\n        <i>{{ panel.comments|default_if_none:"---" }}</i>\n    </div>\n</div>\n</div>'),
        ),
    ]
