# Generated by Django 4.0.4 on 2023-02-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NursingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.JSONField(default=dict)),
                ('updated_by', models.JSONField(default=dict)),
                ('order_id', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(verbose_name='order_description')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SCHEDULED', 'Scheduled'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=256, verbose_name='task_status')),
                ('station', models.JSONField(default=dict)),
                ('tasks', models.JSONField(default=list, verbose_name='nursing_tasks')),
                ('patient', models.JSONField(default=dict)),
                ('closed_by', models.JSONField(default=dict)),
                ('closed_at', models.DateTimeField(null=True)),
                ('cancelled_by', models.JSONField(default=dict)),
                ('cancelled_at', models.DateTimeField(null=True)),
                ('disposition', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'NursingOrders',
                'permissions': (('close_order', 'Can complete order'), ('cancel_order', 'Can cancel order'), ('add_task', 'Can add task '), ('remove_task', 'Can remove task'), ('change_task', 'Can change task'), ('view_task', 'Can view task')),
            },
        ),
        migrations.CreateModel(
            name='NursingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.JSONField(default=dict)),
                ('updated_by', models.JSONField(default=dict)),
                ('name', models.CharField(max_length=256, verbose_name='service_name')),
                ('description', models.TextField(blank=True, null=True)),
                ('bill_item_code', models.CharField(blank=True, max_length=256, null=True)),
                ('audit_log', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name_plural': 'NursingServices',
            },
        ),
        migrations.CreateModel(
            name='NursingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.JSONField(default=dict)),
                ('updated_by', models.JSONField(default=dict)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'NursingStations',
            },
        ),
    ]
