# Generated by Django 4.0.4 on 2022-09-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clinicaldiagnosis_template'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClinicalDiagnosis',
            new_name='Diagnosis',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='diagnosis',
            new_name='case',
        ),
    ]
