# Generated by Django 4.0.4 on 2022-09-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_clinicaldiagnosis_diagnosis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ServiceArm',
            },
        ),
    ]
