# Generated by Django 4.0.4 on 2022-10-28 13:21

import api.apps.core.models
from django.db import migrations, models
import django.utils.timezone
from config.preferences import  AppPreferencesDataTypes, AppPrefenrencesCategories

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicearm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('type', models.CharField(choices=[('INT', 'int'), ('STR', 'str'), ('BOOL', 'bool'), ('FLOAT', 'float')], default=AppPreferencesDataTypes['STR'], max_length=256)),
                ('value', models.CharField(max_length=256, null=True)),
                ('category', models.CharField(choices=[('GENERAL', 'GENERAL'), ('PATIENT', 'PATIENT'), ('FINANCE', 'FINANCE'), ('ENCOUNTER', 'ENCOUNTER'), ('LABORATORY', 'LABORATORY'), ('IMAGING', 'IMAGING')], default=api.apps.core.models.AppPrefenrencesCategories['GENERAL'], max_length=128)),
            ],
            options={
                'verbose_name_plural': 'ApplicationConfigurations',
            },
        ),
        migrations.AddField(
            model_name='template',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='created_by',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='template',
            name='source',
            field=models.CharField(choices=[('ENCOUNTERS', 'Encounter'), ('IMAGING', 'Imaging'), ('LABORATORY', 'Laboratory'), ('INVENTORY', 'Inventory')], default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='template',
            name='updated_by',
            field=models.JSONField(default=dict),
        ),
    ]
