# Generated by Django 4.0.4 on 2022-11-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appconfiguration_template_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('type', models.CharField(choices=[('int', 'Int'), ('str', 'Str'), ('bool', 'Bool'), ('float', 'Float')], default='str', max_length=256)),
                ('value', models.CharField(max_length=256, null=True)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('PATIENT', 'Patient'), ('FINANCE', 'Finance'), ('ENCOUNTER', 'Encounter'), ('LABORATORY', 'Laboratory'), ('IMAGING', 'Imaging'), ('INVENTORY', 'Inventory'), ('PHARMACY', 'Pharmacy')], default='GENERAL', max_length=128)),
            ],
            options={
                'verbose_name_plural': 'ApplicationPrefencess',
            },
        ),
        migrations.DeleteModel(
            name='AppConfiguration',
        ),
        migrations.AlterField(
            model_name='template',
            name='source',
            field=models.CharField(choices=[('ENCOUNTERS', 'Encounter'), ('IMAGING', 'Imaging'), ('LABORATORY', 'Laboratory'), ('INVENTORY', 'Inventory'), ('PHARMACY', 'Pharmacy')], max_length=128),
        ),
    ]
