# Generated by Django 4.0.4 on 2022-11-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_apppreferences_delete_appconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppreferences',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('PATIENT', 'Patient'), ('FINANCE', 'Finance'), ('ENCOUNTER', 'Encounter'), ('LABORATORY', 'Laboratory'), ('IMAGING', 'Imaging'), ('INVENTORY', 'Inventory'), ('PHARMACY', 'Pharmacy'), ('NURSING', 'Nursing')], default='GENERAL', max_length=128),
        ),
        migrations.AlterField(
            model_name='template',
            name='source',
            field=models.CharField(choices=[('ENCOUNTERS', 'Encounter'), ('IMAGING', 'Imaging'), ('LABORATORY', 'Laboratory'), ('INVENTORY', 'Inventory'), ('PHARMACY', 'Pharmacy'), ('NURSING', 'Nursing')], max_length=128),
        ),
    ]
