# Generated by Django 4.0.4 on 2022-12-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_apppreferences_category_alter_template_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'DocumentTypes',
            },
        ),
        migrations.AlterField(
            model_name='apppreferences',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('PATIENT', 'Patient'), ('FINANCE', 'Finance'), ('ENCOUNTER', 'Encounter'), ('LABORATORY', 'Laboratory'), ('IMAGING', 'Imaging'), ('INVENTORY', 'Inventory'), ('PHARMACY', 'Pharmacy'), ('NURSING', 'Nursing'), ('REPORTS', 'Reports')], default='GENERAL', max_length=128),
        ),
        migrations.AlterField(
            model_name='apppreferences',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
