# Generated by Django 4.0.4 on 2022-11-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.JSONField(default=dict)),
                ('updated_by', models.JSONField(default=dict)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Templates',
            },
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'permissions': (('fulfill_prescription', 'Can fulfill prescription'), ('cancel_prescription', 'Can cancel prescription')), 'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='note',
        ),
        migrations.AddField(
            model_name='prescription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='cancelled_by',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='prescription',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='fulfilled_by',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=256),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribing_physician',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='source',
            field=models.CharField(choices=[('OPD', 'Opd'), ('IPD', 'Ipd'), ('NS', 'Ns')], max_length=256),
        ),
    ]
