# Generated by Django 4.0.4 on 2022-12-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_template_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'permissions': (('confirm_prescription', 'Can confirm prescription'), ('cancel_prescription', 'Can cancel prescription'), ('download_prescription', 'Can download prescription'), ('mail_prescription', 'Can mail prescription')), 'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='fulfilled_at',
            new_name='confirmed_at',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='fulfilled_by',
            new_name='confirmed_by',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=256),
        ),
    ]
