# Generated by Django 4.0.4 on 2023-02-23 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_name_alter_store_type_and_more'),
        ('pharmacy', '0003_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.JSONField(default=dict)),
                ('updated_by', models.JSONField(default=dict)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('inv_store', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.store')),
            ],
            options={
                'verbose_name_plural': 'Pharmacy Stores',
            },
        ),
    ]
