# Generated by Django 4.0.4 on 2022-06-11 11:20

from django.db import migrations, models
from api.apps.patient import models as pat_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(default=pat_models.generate_uhid, editable=False, max_length=50, unique=True)),
                ('is_baby', models.BooleanField(default=False)),
                ('salutation', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('state_id', models.JSONField()),
                ('home_address', models.JSONField()),
                ('next_of_kin', models.JSONField()),
                ('lga', models.CharField(max_length=255)),
                ('identity', models.JSONField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('payment_scheme', models.JSONField(blank=True, null=True)),
                ('profile_picture', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
