# Generated by Django 4.0.4 on 2022-08-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_payment_scheme_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': (('patient_deposit', 'Can deposit to patient'),), 'verbose_name_plural': 'Patients'},
        ),
        migrations.AddField(
            model_name='patient',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='reserve',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
