# Generated by Django 4.0.4 on 2022-09-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patient_created_at_patientfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='service_arm',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='service_arm_no',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
