# Generated by Django 4.0.4 on 2022-07-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='bill_item_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='bill',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='signed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='chief_complaint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(default='Walk In', max_length=255),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='patient',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='provider',
            field=models.JSONField(default=dict),
        ),
    ]
