# Generated by Django 4.0.4 on 2022-07-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_clinic_bill_item_code_encounter_bill_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounter',
            options={'ordering': ['-created_datetime'], 'permissions': (('take_vitals', 'Can take vitals'), ('sign_encounter', 'Can sign encounter')), 'verbose_name_plural': 'Encounters'},
        ),
    ]
