# Generated by Django 4.0.4 on 2022-09-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0003_alter_encounter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounter',
            options={'ordering': ['-created_datetime'], 'permissions': (('take_vitals', 'Can take vitals'), ('sign_encounter', 'Can sign encounter'), ('acknowledge_encounter', 'Can acknowledge encounter')), 'verbose_name_plural': 'Encounters'},
        ),
        migrations.AddField(
            model_name='encounter',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='acknowledged_by',
            field=models.JSONField(default=dict),
        ),
    ]
