# Generated by Django 4.0.4 on 2022-09-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0004_alter_encounter_options_encounter_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='audit_log',
            field=models.JSONField(default=list),
        ),
    ]
