# Generated by Django 4.0.4 on 2022-10-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0005_encounter_audit_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='Department',
            new_name='department',
        ),
    ]
