# Generated by Django 4.0.4 on 2022-11-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0006_rename_department_clinic_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='signed_by',
            field=models.JSONField(default=dict),
        ),
    ]
