# Generated by Django 4.0.4 on 2023-01-05 10:58

import api.includes.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0007_encounter_signed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.JSONField(default=dict)),
                ('updated_by', models.JSONField(default=dict)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.JSONField(default=list)),
                ('is_private', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'EncounterTemplates',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='time_log',
        ),
        migrations.AddField(
            model_name='encounter',
            name='legacy_chart',
            field=models.JSONField(default=api.includes.utils.jsonfield_default_value),
        ),
        migrations.AddField(
            model_name='encounter',
            name='orders',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='encounter',
            name='vitals',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='chart',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
