# Generated by Django 4.0.4 on 2023-01-05 12:28

import api.apps.encounters.utils
import api.includes.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0008_encountertemplate_delete_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='chart',
            field=models.JSONField(default=api.includes.utils.jsonfield_default_value),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_id',
            field=models.CharField(default=api.apps.encounters.utils.generate_encounter_id, editable=False, max_length=50, unique=True),
        ),
    ]
