# Generated by Django 4.0.4 on 2023-02-13 14:45

import api.apps.encounters.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0009_alter_encounter_chart_alter_encounter_encounter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encountertemplate',
            old_name='is_private',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='clinic',
            name='templates',
            field=models.ManyToManyField(to='encounters.encountertemplate'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='bill_package_usage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='diagnosis',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='encountertemplate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='chart',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_id',
            field=models.CharField(blank=True, default=api.apps.encounters.utils.generate_encounter_id, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
