# Generated by Django 4.0.4 on 2022-06-11 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(editable=False, max_length=256, unique=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('module', models.CharField(choices=[('ENCOUNTERS', 'encounters'), ('IMAGING', 'imaging'), ('LABORATORY', 'laboratory')], max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.JSONField(default=dict)),
                ('updated_by', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'Billable Items',
            },
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Payers',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('created_by', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'Price Lists',
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_item_code', models.CharField(max_length=256)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co_pay', models.JSONField(default=dict)),
                ('is_auth_req', models.BooleanField(default=False)),
                ('is_capitated', models.BooleanField(default=False)),
                ('created_by', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.pricelist')),
            ],
            options={
                'verbose_name_plural': 'Price List Items',
            },
        ),
        migrations.CreateModel(
            name='PayerScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_by', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.payer')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.pricelist')),
            ],
            options={
                'verbose_name_plural': 'Payer Schemes',
            },
        ),
    ]
