# Generated by Django 4.0.4 on 2022-07-09 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.AddField(
            model_name='payerscheme',
            name='type',
            field=models.CharField(choices=[('SELF', 'SELF'), ('INSURANCE', 'INSURANCE')], default='SELF', max_length=256),
        ),
        migrations.AlterField(
            model_name='billableitem',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='billableitem',
            name='module',
            field=models.CharField(choices=[('ENCOUNTERS', 'Encounter'), ('IMAGING', 'Imaging'), ('LABORATORY', 'Laboratory')], max_length=256),
        ),
        migrations.AlterField(
            model_name='billableitem',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bills', models.JSONField(default=list)),
                ('patient', models.JSONField(default=dict)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('audit_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.paymentmethod')),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_item_code', models.CharField(max_length=256)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cleared_status', models.CharField(choices=[('CLEARED', 'CLEARED'), ('UNCLEARED', 'UNCLEARED')], max_length=256)),
                ('quantity', models.IntegerField(default=1)),
                ('bill_source', models.CharField(max_length=256)),
                ('billed_to_type', models.CharField(choices=[('SELF', 'SELF'), ('INSURANCE', 'INSURANCE')], max_length=256)),
                ('co_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_center', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_service_rendered', models.BooleanField(default=False)),
                ('is_invoiced', models.BooleanField(default=False)),
                ('is_capitated', models.BooleanField(default=False)),
                ('auth_code', models.CharField(blank=True, max_length=256, null=True)),
                ('patient', models.JSONField(default=dict)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('billed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.payerscheme')),
            ],
        ),
    ]
