# Generated by Django 4.0.4 on 2022-08-02 17:03

import api.apps.finance.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_paymentmethod_payerscheme_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True, null=True)),
                ('encounter', models.IntegerField(blank=True, null=True)),
                ('encounter_type', models.CharField(blank=True, choices=[('IN_PATIENT', 'IN PATIENT'), ('OUT_PATIENT', 'OUT PATIENT')], max_length=256, null=True)),
                ('patient', models.JSONField(default=dict)),
                ('bill_lines', models.JSONField(default=list)),
                ('payment_lines', models.JSONField(default=list)),
                ('total_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('OPEN', 'OPEN'), ('PARTIAL_PAY', 'PARTIAL_PAY'), ('PAID', 'PAID')], default=api.apps.finance.models.InvoiceStatus['DRAFT'], max_length=256)),
                ('payer_scheme', models.JSONField(default=dict)),
                ('due_date', models.DateTimeField()),
                ('confirmed_by', models.JSONField(default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.JSONField(default=dict)),
                ('updated_by', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name_plural': 'Bills'},
        ),
        migrations.AddField(
            model_name='bill',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payer',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('INVOICE', 'INVOICE')], default='DEPOSIT', max_length=256),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='is_exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='module',
            field=models.CharField(choices=[('ENCOUNTERS', 'Encounter'), ('IMAGING', 'Imaging'), ('LABORATORY', 'Laboratory')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='post_auth_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payerscheme',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.pricelist'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method'
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.invoice'),
        ),
    ]
