# Generated by Django 4.0.4 on 2022-08-11 14:38

import api.apps.finance.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_invoice_alter_bill_options_bill_is_reserved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'permissions': (('add_bill', 'Can add bill'), ('remove_bill', 'Can remove bill')), 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AddField(
            model_name='bill',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('OPEN', 'OPEN'), ('PARTIAL_PAY', 'PARTIAL_PAY'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED')], default=api.apps.finance.models.InvoiceStatus['DRAFT'], max_length=256),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('INVOICE', 'INVOICE'), ('RESERVE', 'RESERVE'), ('REFUND', 'REFUND')], default='DEPOSIT', max_length=256),
        ),
    ]
