# Generated by Django 4.0.4 on 2022-09-08 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_bill_serviced_rendered_at_invoice_inv_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'permissions': (('authorize_bills', 'Can authorize insurance bills'), ('pay_bills', 'Can accept payment for bills')), 'verbose_name_plural': 'Bills'},
        ),
        migrations.AddField(
            model_name='bill',
            name='is_auth_req',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='updated_by',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='bill',
            name='billed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.payerscheme'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.invoice'),
        ),
        migrations.RemoveField(
           model_name='invoice',
           name='payer_scheme'
        ),
        migrations.AddField(
            model_name='invoice',
            name='payer_scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.payerscheme'),
        ),
        migrations.AlterField(
            model_name='payerscheme',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.payer'),
        ),
        migrations.AlterField(
            model_name='payerscheme',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.pricelist'),
        ),
    ]
