# Generated by Django 4.0.4 on 2022-09-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_bill_options_bill_is_auth_req_bill_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'permissions': (('authorize_bills', 'Can authorize insurance bills'), ('pay_bills', 'Can accept payment for bills'), ('transfer_bill', 'Can transfer bill to different schemes'), ('reserve_bill', 'Can reserve bill'), ('unreserve_bill', 'Can unreserve bill')), 'verbose_name_plural': 'Bills'},
        ),
        migrations.AddField(
            model_name='bill',
            name='post_auth_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
