# Generated by Django 4.0.4 on 2022-09-16 15:37

import api.apps.finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_bill_options_bill_post_auth_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csb_id', models.CharField(max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default=api.apps.finance.models.CashBookStatus['OPEN'], max_length=256)),
                ('created_by', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cashbooks',
            },
        ),
    ]
