# Generated by Django 4.0.4 on 2022-10-28 13:21

import api.apps.finance.models.invoice
import api.apps.finance.models.payer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_cashbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'permissions': (('authorize_bills', 'Can authorize insurance bills'), ('transfer_bill', 'Can transfer bill to different schemes'), ('reserve_bill', 'Can reserve bill'), ('unreserve_bill', 'Can unreserve bill')), 'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'permissions': (('add_bill', 'Can add bill'), ('remove_bill', 'Can remove bill'), ('edit_bill', 'Can edit bills'), ('markup_price', 'Can increase price'), ('markdown_price', 'Can reduce price'), ('confirm_invoice', 'Can confirm invoice')), 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': (('accept_payment', 'Can accept payments'),), 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_source',
            field=models.CharField(choices=[('ENCOUNTERS', 'Encounter'), ('IMAGING', 'Imaging'), ('LABORATORY', 'Laboratory'), ('INVENTORY', 'Inventory')], max_length=256),
        ),
        migrations.AlterField(
            model_name='bill',
            name='billed_to_type',
            field=models.CharField(choices=[('SELF_PREPAID', 'SELF (PREPAID)'), ('SELF_POSTPAID', 'SELF (POSTPAID)'), ('INSURANCE', 'INSURANCE'), ('CORPORATE', 'CORPORATE')], max_length=256),
        ),
        migrations.AlterField(
            model_name='billableitem',
            name='module',
            field=models.CharField(choices=[('ENCOUNTERS', 'Encounter'), ('IMAGING', 'Imaging'), ('LABORATORY', 'Laboratory'), ('INVENTORY', 'Inventory')], max_length=256),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='scheme_type',
            field=models.CharField(choices=[('SELF_PREPAID', 'SELF (PREPAID)'), ('SELF_POSTPAID', 'SELF (POSTPAID)'), ('INSURANCE', 'INSURANCE'), ('CORPORATE', 'CORPORATE')], default=api.apps.finance.models.payer.PayerSchemeType['SELF_PREPAID'], max_length=256),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('OPEN', 'OPEN'), ('PARTIALLY_PAID', 'PARTIALLY_PAID'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED')], default=api.apps.finance.models.invoice.InvoiceStatus['DRAFT'], max_length=256),
        ),
        migrations.AlterField(
            model_name='payerscheme',
            name='type',
            field=models.CharField(choices=[('SELF_PREPAID', 'SELF (PREPAID)'), ('SELF_POSTPAID', 'SELF (POSTPAID)'), ('INSURANCE', 'INSURANCE'), ('CORPORATE', 'CORPORATE')], default='SELF (PREPAID)', max_length=256),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='module',
            field=models.CharField(choices=[('ENCOUNTERS', 'Encounter'), ('IMAGING', 'Imaging'), ('LABORATORY', 'Laboratory'), ('INVENTORY', 'Inventory')], max_length=256, null=True),
        ),
    ]
