# Generated by Django 4.0.4 on 2022-11-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_bill_options_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_source',
            field=models.CharField(choices=[('ENCOUNTERS', 'Encounter'), ('IMAGING', 'Imaging'), ('LABORATORY', 'Laboratory'), ('INVENTORY', 'Inventory'), ('PHARMACY', 'Pharmacy')], max_length=256),
        ),
        migrations.AlterField(
            model_name='billableitem',
            name='module',
            field=models.CharField(choices=[('ENCOUNTERS', 'Encounter'), ('IMAGING', 'Imaging'), ('LABORATORY', 'Laboratory'), ('INVENTORY', 'Inventory'), ('PHARMACY', 'Pharmacy')], max_length=256),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='module',
            field=models.CharField(choices=[('ENCOUNTERS', 'Encounter'), ('IMAGING', 'Imaging'), ('LABORATORY', 'Laboratory'), ('INVENTORY', 'Inventory'), ('PHARMACY', 'Pharmacy')], max_length=256, null=True),
        ),
    ]
