# Generated by Django 4.0.4 on 2022-11-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_bill_bill_source_alter_billableitem_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_source',
            field=models.CharField(choices=[('ENCOUNTERS', 'Encounter'), ('IMAGING', 'Imaging'), ('LABORATORY', 'Laboratory'), ('INVENTORY', 'Inventory'), ('PHARMACY', 'Pharmacy'), ('NURSING', 'Nursing')], max_length=256),
        ),
        migrations.AlterField(
            model_name='billableitem',
            name='module',
            field=models.CharField(choices=[('ENCOUNTERS', 'Encounter'), ('IMAGING', 'Imaging'), ('LABORATORY', 'Laboratory'), ('INVENTORY', 'Inventory'), ('PHARMACY', 'Pharmacy'), ('NURSING', 'Nursing')], max_length=256),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='module',
            field=models.CharField(choices=[('ENCOUNTERS', 'Encounter'), ('IMAGING', 'Imaging'), ('LABORATORY', 'Laboratory'), ('INVENTORY', 'Inventory'), ('PHARMACY', 'Pharmacy'), ('NURSING', 'Nursing')], max_length=256, null=True),
        ),
    ]
