# Generated by Django 4.0.4 on 2022-12-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_bill_bill_source_alter_billableitem_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_by',
            field=models.JSONField(default=dict),
        ),
    ]
