# Generated by Django 4.0.4 on 2023-01-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_invoice_cancelled_at_invoice_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.JSONField(default=dict),
        ),
    ]
