# Generated by Django 4.0.4 on 2023-02-13 14:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_payment_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.JSONField(default=dict)),
                ('updated_by', models.JSONField(default=dict)),
                ('package_code', models.CharField(editable=False, max_length=256, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('validity_duration', models.BigIntegerField(verbose_name='duration_days')),
                ('billable_items', models.JSONField(default=list)),
                ('bill_item_code', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bill Packages',
            },
        ),
        migrations.CreateModel(
            name='PatientBillPackageSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.JSONField(default=dict)),
                ('updated_by', models.JSONField(default=dict)),
                ('patient', models.JSONField(default=dict)),
                ('bill_package', models.JSONField(default=dict)),
                ('expiration_date', models.DateTimeField(editable=False, null=True)),
                ('bill', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'PatientBillPackageSubcsriptions',
            },
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_source',
            field=models.CharField(choices=[('ENCOUNTERS', 'Encounter'), ('IMAGING', 'Imaging'), ('LABORATORY', 'Laboratory'), ('INVENTORY', 'Inventory'), ('PHARMACY', 'Pharmacy'), ('NURSING', 'Nursing'), ('FINANCE', 'Finance'), ('MESSAGING', 'Messaging')], max_length=256),
        ),
        migrations.AlterField(
            model_name='billableitem',
            name='module',
            field=models.CharField(choices=[('ENCOUNTERS', 'Encounter'), ('IMAGING', 'Imaging'), ('LABORATORY', 'Laboratory'), ('INVENTORY', 'Inventory'), ('PHARMACY', 'Pharmacy'), ('NURSING', 'Nursing'), ('FINANCE', 'Finance'), ('MESSAGING', 'Messaging')], max_length=256),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='module',
            field=models.CharField(choices=[('ENCOUNTERS', 'Encounter'), ('IMAGING', 'Imaging'), ('LABORATORY', 'Laboratory'), ('INVENTORY', 'Inventory'), ('PHARMACY', 'Pharmacy'), ('NURSING', 'Nursing'), ('FINANCE', 'Finance'), ('MESSAGING', 'Messaging')], max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='PatientBillPackageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billable_item', models.JSONField(default=dict)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('is_service_renderded', models.BooleanField(default=False)),
                ('package_subscription', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscription', to='finance.patientbillpackagesubscription')),
            ],
            options={
                'verbose_name_plural': 'PatientBillPackageUsages',
            },
        ),
    ]
