# Generated by Django 4.0.4 on 2023-02-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_billpackage_patientbillpackagesubscription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientbillpackageusage',
            old_name='is_service_renderded',
            new_name='is_service_rendered',
        ),
    ]
