# Generated by Django 4.0.4 on 2022-06-11 11:20

from django.db import migrations, models
import django.db.models.deletion
from api.apps.imaging import models as img_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.JSONField(default=dict)),
                ('img_id', models.CharField(default=img_models.generate_imaging_order_id, max_length=256, unique=True)),
                ('stat', models.BooleanField(default=False)),
                ('service_center', models.JSONField()),
                ('referral_facility', models.JSONField(blank=True, null=True)),
                ('comments', models.TextField()),
                ('img_obv', models.JSONField(default=list)),
                ('img_obv_orders', models.JSONField(default=list)),
                ('ordered_by', models.JSONField(default=dict)),
                ('ordered_datetime', models.DateTimeField(auto_now_add=True)),
                ('ordering_physician', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('order_no', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagingObservationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.CharField(default=img_models.generate_imaging_obv_order_id, max_length=256, unique=True)),
                ('img_obv', models.JSONField(default=dict)),
                ('status', models.CharField(blank=True, max_length=256, null=True)),
                ('audit_log', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('img_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imaging.imagingorder')),
            ],
        ),
        migrations.CreateModel(
            name='ImagingObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, max_length=256, null=True)),
                ('audit_log', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('img_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imaging.imagingunit')),
            ],
        ),
    ]
