# Generated by Django 4.0.4 on 2022-07-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0002_rename_imagingunit_modality_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagingobservationorder',
            options={'permissions': (('capture_imaging', 'Can capture imaging'), ('submit_imaging', 'Can submit imaging'), ('approve_reject_imaging', 'Can approve or reject imaging'))},
        ),
    ]
