# Generated by Django 4.0.4 on 2022-07-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0003_alter_imagingobservationorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagingobservationorder',
            options={'permissions': (('capture_imaging', 'Can capture imaging'), ('submit_imaging', 'Can submit imaging'), ('approve_reject_imaging', 'Can approve or reject imaging'), ('mail_print_result', 'Can mail or print result'))},
        ),
        migrations.AddField(
            model_name='imagingobservationorder',
            name='is_result_sent',
            field=models.BooleanField(default=False),
        ),
    ]
