# Generated by Django 4.0.4 on 2022-10-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0004_alter_imagingobservationorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingorder',
            name='diagnosis',
            field=models.JSONField(default=list, null=True),
        ),
    ]
