# Generated by Django 4.0.4 on 2022-12-09 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0005_imagingorder_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingObserverOrderAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.JSONField(default=dict)),
                ('updated_by', models.JSONField(default=dict)),
                ('file_path', models.CharField(max_length=256)),
                ('img_obv_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imaging.imagingobservationorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
