# Generated by Django 4.0.4 on 2023-02-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0006_imagingobserverorderattachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingobservationorder',
            name='bill_package_usage',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
